---
name: 'Rails: All _id Columns Must Be Indexed'
description: >
  Ensures all foreign key columns in Rails apps have corresponding database
  indexes
author: 'Nate Berkopec / The Speedshop'

inputs:
  debug:
    description: 'Enable debug output'
    required: false
    default: '0'
  schema_file:
    description: 'Path to schema.rb'
    required: true
    default: './db/schema.rb'

runs:
  using: 'composite'
  steps:
    - name: Check migrations for missing indexes
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        SCHEMA_FILE: ${{ inputs.schema_file }}
      run: ${{ github.action_path }}/check_indexes.sh
